version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/usr/src/app
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/rechnungsapp

  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
